# Generated by Django 6.1 on 2026-09-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_new_roles'),
        ('core', '0010_add_restaurant_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='The restaurant this employee belongs to. Null for platform admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.restaurant'),
        ),
    ]
