# Generated by Django 6.1 on 2026-08-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('SUPPLIES', 'Supplies'), ('RENT', 'Rent'), ('SALARIES', 'Salaries'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('spent_on', models.DateField()),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
            },
        ),
    ]
