# Generated by Django 6.1 on 2026-08-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('orders', '0005_order_orders_orde_order_t_1378c7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('ORDER_READY', 'Order Ready')], default='ORDER_READY', max_length=30)),
                ('message', models.TextField()),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cabin_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(db_index=True, default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.orderbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dismissed', 'created_at'], name='core_notifi_dismiss_22a186_idx')],
            },
        ),
    ]
