# Generated by Django 6.1 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restaurant_settings_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_employees',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='restaurant', help_text="Unique identifier used for login and URLs (e.g., 'my-restaurant').", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
    ]
